version: '3.8'

x-cache-from:
  - &app-cache-from
    cache_from:
      - php:8.0-fpm

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_PASSWORD: symfony
      MYSQL_DB: symfony
      MYSQL_USER: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "3306:3306"

  php:
    image: php:8.0-fpm
    build:
      context: ./docker/php-fpm
      <<: *app-cache-from
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - ./symfony:/var/www
      - app-cache:/var/www/var

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./symfony:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  adminer:
    depends_on:
      - mailcatcher
      - db
    image: adminer
    ports:
      - 8080:8080

  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8888:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
volumes:
  db-data: {}
  app-cache: {}
