vich_uploader:
    db_driver: orm

    mappings:
        brand_documents:
            uri_prefix:         '%app.path.brand_documents%'
            upload_destination: '%kernel.project_dir%/public%app.path.brand_documents%'
